var str =  "Adfar Adfar Adfar Adfar Rasheed     "
console.log(str.length)
var b = str.slice(2,6)
console.log(b)
var c = str.slice(4,10000)
console.log(c)
var d = str.substring(2,6)
console.log(d)
var e = str.substr(2,6)
console.log( e)
var f = str.replace("Adfar","adfarrr")
console.log(f)
var g = str.replaceAll("Adfar","adfarrr")
console.log(g)
var h = str.trim()
console.log(h)
var i = str.split(" ")
console.log(i)