const students = [{
    "id": 1,
    "first_name": "Kimmy",
    "last_name": "Kaygill",
    "email": "kkaygill0@newyorker.com"
  }, {
    "id": 2,
    "first_name": "Priscilla",
    "last_name": "Telezhkin",
    "email": "ptelezhkin1@linkedin.com"
  }, {
    "id": 3,
    "first_name": "Stephine",
    "last_name": "Tran",
    "email": "stran2@amazon.com"
  }, {
    "id": 4,
    "first_name": "Ines",
    "last_name": "Whitlam",
    "email": "iwhitlam3@webmd.com"
  }, {
    "id": 5,
    "first_name": "Jule",
    "last_name": "Miners",
    "email": "jminers4@google.pl"
  }, {
    "id": 6,
    "first_name": "Emmaline",
    "last_name": "Broseke",
    "email": "ebroseke5@china.com.cn"
  }, {
    "id": 7,
    "first_name": "Nat",
    "last_name": "Lacelett",
    "email": "nlacelett6@amazon.co.uk"
  }, {
    "id": 8,
    "first_name": "Bastien",
    "last_name": "Moresby",
    "email": "bmoresby7@nifty.com"
  }, {
    "id": 9,
    "first_name": "Hadrian",
    "last_name": "Collete",
    "email": "hcollete8@statcounter.com"
  }, {
    "id": 10,
    "first_name": "Doris",
    "last_name": "Tomalin",
    "email": "dtomalin9@artisteer.com"
  }]
  module.exports = students